### ISSUE TITLE
Grammar coverage checklist

### ISSUE THREAD

**Issue by smashwilson** [smashwilson/segment#6]
This is a master list of the grammar constructs that need representation in the AST.
- [x] Statement lists.
- [x] Integer literals.
- [ ] Float literals.
- [x] Strings.
- [ ] Symbols.
- [ ] Regular expressions.
- [x] Blocks.
- [x] ...with parameters.
- [ ] Default block parameters.
- [ ] Assignment.
- [ ] Temporary variables.
- [ ] Instance variables.
- [x] Binary operators.
- [x] ... `ANDLIKE`.
- [x] ... `ORLIKE`.
- [x] ... `PLUSLIKE`.
- [x] ... `MINUSLIKE`.
- [x] ... `MULTLIKE`.
- [x] ... `DIVLIKE`.
- [x] ... `MODLIKE`.
- [x] ... `EXPLIKE`.
- [ ] `NOT` unary operator.
- [x] method calls:
- [x] ...with implicit receiver. 
- [x] ...with explicit receiver.
- [x] ...comma-separated argument lists
- [x] ...space-separated argument lists

Concepts that haven't made it in to the lexer or grammar yet, and general cleanup.
- [x] String interpolation.
- [ ] Parallel assignment.
- [ ] Varargs and kwargs.
- [ ] Unary minus.
- [x] Flatten `invocation` into `expr`.
